version: '3'

services:
  php-fpm-md:
      build:
        context: .
        dockerfile: Dockerfile
        target: php_app_md_group
      image: php-md-group
      container_name: md-app
      volumes:
        - .:/var/www/html
      ports:
        - "9000:9000"
  nginx-md:
      image: nginx:alpine
      container_name: md-nginx
      depends_on:
        - php-fpm-md
      build:
        context: .
        dockerfile: Dockerfile
        target: md-nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: md-group
      MYSQL_ROOT_PASSWORD: root_pass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
